export interface TemplateCtx {
  pad: { x: number; y: number };
  PX: number;
  PY: number;
  P: string;
  PD: string;
  FONT_STACK_ACTIVE: string;
  GRAD: string;
  OUTER: string;
  GRAD_H2: string;
  GRAD_H1: string;
  GRAD_SUMMARY: string;
  GRAD_H3_CARD: string;
  GRAD_TEXT: string;
  icon0: string;
  icon1: string;
  icon2: string;
  icon3: string;
  icon4: string;
  li0: (text: string) => string;
  li1: (text: string) => string;
  li2: (text: string) => string;
  li3: (text: string) => string;
  li4: (text: string) => string;
  useEmojiBigIcons: boolean;
  useLineBigIcons: boolean;
  useFilledBigIcons: boolean;
  getBigIcon: (idx: number, size: number, iconSize: number) => string;
  tocIcon0: string;
  tocIcon1: string;
  tocIcon2: string;
  cardIcon0: string;
  cardIcon1: string;
  cardIcon2: string;
  cardIcon3: string;
  listCardIcon0: string;
  listCardIcon1: string;
  listCardIcon2: string;
  listCardIcon3: string;
  gridCardIcon0: string;
  gridCardIcon1: string;
  gridCardIcon2: string;
  gridCardIcon3: string;
  tlIcon0: string;
  tlIcon1: string;
  tlIcon2: string;
  zigzagIcon1: string;
  zigzagIcon2: string;
  cmpRight: string;
  cmpLeft: string;
}
